"""
GitHub Organization Governance — infrastructure-as-policy.

All functions are idempotent. Applies:
1. Team creation with member assignments
2. Repo-level team permissions
3. Branch protection rules
4. CODEOWNERS files
5. PR/Issue templates

Reads governance policy from config, executes via github_admin tool.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.services import integration as integration_service
from app.tools import github_admin

logger = logging.getLogger(__name__)


# ── Policy Configuration ─────────────────────────────────────────────────────

@dataclass
class TeamPolicy:
    name: str
    slug: str
    description: str
    members: list[str]
    repo_permission: str  # pull, push, admin, maintain, triage


@dataclass
class BranchProtectionPolicy:
    required_approvals: int = 1
    require_code_owner_reviews: bool = True
    dismiss_stale_reviews: bool = True
    require_status_checks: bool = True
    block_force_pushes: bool = True
    restrict_push_teams: list[str] = field(default_factory=list)


@dataclass
class GovernancePolicy:
    org: str
    teams: list[TeamPolicy]
    branch_protection: BranchProtectionPolicy
    critical_repos: list[str]  # repos that get stricter rules (2 approvals)
    codeowners_content: str
    pr_template: str
    bug_template: str
    feature_template: str


def build_empireoe_policy() -> GovernancePolicy:
    """Build the governance policy for empireoe-ai."""
    org = (settings.GITHUB_ORG or "empireoe-ai").strip()
    tech_leads = [u.strip() for u in settings.GITHUB_TECH_LEADS.split(",") if u.strip()]
    developers = [u.strip() for u in settings.GITHUB_DEVELOPERS.split(",") if u.strip()]

    return GovernancePolicy(
        org=org,
        teams=[
            TeamPolicy(
                name="tech-leads",
                slug="tech-leads",
                description="Technical leads — admin access on all repos",
                members=tech_leads,
                repo_permission="admin",
            ),
            TeamPolicy(
                name="developers",
                slug="developers",
                description="Development team — write access on all repos",
                members=developers,
                repo_permission="push",
            ),
        ],
        branch_protection=BranchProtectionPolicy(
            required_approvals=1,
            require_code_owner_reviews=True,
            dismiss_stale_reviews=True,
            require_status_checks=True,
            block_force_pushes=True,
            restrict_push_teams=["tech-leads"],
        ),
        critical_repos=[r.strip() for r in (settings.CRITICAL_GITHUB_REPOS or "").split(",") if r.strip()],
        codeowners_content=(
            "# Code Owners — auto-generated by governance automation\n"
            "# Tech lead must approve all changes\n"
            "* @sharonempire\n"
            "\n"
            "# Critical paths require owner approval too\n"
            "/.github/ @nidin-cyber @sharonempire\n"
            "/deploy/ @nidin-cyber @sharonempire\n"
            "*.env* @nidin-cyber\n"
        ),
        pr_template=(
            "## What does this PR do?\n"
            "<!-- Brief description -->\n"
            "\n"
            "## Linked Task\n"
            "<!-- ClickUp task URL or ID -->\n"
            "\n"
            "## Checklist\n"
            "- [ ] Tests added/updated\n"
            "- [ ] No console.log / debug code left\n"
            "- [ ] Screenshots attached (if UI change)\n"
            "- [ ] Database migration included (if schema change)\n"
            "- [ ] Reviewed my own diff before requesting review\n"
        ),
        bug_template=(
            "---\n"
            "name: Bug Report\n"
            "about: Report a bug\n"
            "labels: bug\n"
            "---\n"
            "\n"
            "## Description\n"
            "<!-- What happened? -->\n"
            "\n"
            "## Steps to Reproduce\n"
            "1. \n"
            "2. \n"
            "\n"
            "## Expected Behavior\n"
            "<!-- What should have happened? -->\n"
            "\n"
            "## Actual Behavior\n"
            "<!-- What actually happened? -->\n"
            "\n"
            "## Environment\n"
            "- Browser/OS:\n"
            "- Deployment:\n"
        ),
        feature_template=(
            "---\n"
            "name: Feature Request\n"
            "about: Suggest a new feature\n"
            "labels: enhancement\n"
            "---\n"
            "\n"
            "## Problem\n"
            "<!-- What problem does this solve? -->\n"
            "\n"
            "## Proposed Solution\n"
            "<!-- How should it work? -->\n"
            "\n"
            "## Acceptance Criteria\n"
            "- [ ] \n"
            "\n"
            "## Priority\n"
            "<!-- Low / Medium / High / Critical -->\n"
        ),
    )


# ── Apply Functions ──────────────────────────────────────────────────────────

@dataclass
class GovernanceReport:
    teams: list[dict[str, Any]] = field(default_factory=list)
    permissions: list[dict[str, Any]] = field(default_factory=list)
    branch_protections: list[dict[str, Any]] = field(default_factory=list)
    codeowners: list[dict[str, Any]] = field(default_factory=list)
    templates: list[dict[str, Any]] = field(default_factory=list)
    errors: list[dict[str, Any]] = field(default_factory=list)


async def _get_github_token(db: AsyncSession, org_id: int) -> str | None:
    """Retrieve the stored GitHub PAT for this org."""
    item = await integration_service.get_integration_by_type(db, org_id, "github")
    if not item or item.status != "connected":
        return None
    cfg = item.config_json or {}
    return cfg.get("access_token")


async def apply_governance(
    db: AsyncSession,
    org_id: int,
    policy: GovernancePolicy | None = None,
) -> GovernanceReport:
    """
    Apply full governance policy to the GitHub org. Idempotent.
    Returns a structured report of all actions taken.
    """
    if policy is None:
        policy = build_empireoe_policy()

    token = await _get_github_token(db, org_id)
    if not token:
        return GovernanceReport(errors=[{"step": "auth", "error": "GitHub not connected or no token"}])

    report = GovernanceReport()
    org = policy.org

    # 1. Create teams and add members
    for team in policy.teams:
        try:
            result = await github_admin.ensure_team(
                token, org, team.name, description=team.description,
            )
            report.teams.append({
                "team": team.name, "action": result["action"],
                "members_added": [],
            })
            # Add members
            members_added = []
            for member in team.members:
                try:
                    mr = await github_admin.ensure_team_member(
                        token, org, team.slug, member,
                    )
                    members_added.append(mr)
                except Exception as exc:
                    report.errors.append({
                        "step": "team_member",
                        "team": team.name,
                        "member": member,
                        "error": str(exc),
                    })
            report.teams[-1]["members_added"] = members_added
        except Exception as exc:
            report.errors.append({
                "step": "team_create",
                "team": team.name,
                "error": str(exc),
            })

    # 2. List org repos and apply team permissions
    try:
        repos = await github_admin.list_org_repos(token, org)
    except Exception as exc:
        report.errors.append({"step": "list_repos", "error": str(exc)})
        repos = []

    active_repos = [
        r for r in repos
        if not r.get("archived") and not r.get("disabled")
    ]

    for repo in active_repos:
        full_name = repo.get("full_name", "")
        if not full_name:
            continue

        # Apply team permissions
        for team in policy.teams:
            try:
                pr = await github_admin.ensure_team_repo_permission(
                    token, org, team.slug, full_name, permission=team.repo_permission,
                )
                report.permissions.append(pr)
            except Exception as exc:
                report.errors.append({
                    "step": "repo_permission",
                    "repo": full_name,
                    "team": team.name,
                    "error": str(exc),
                })

        # 3. Branch protection
        default_branch = repo.get("default_branch", "main")
        bp = policy.branch_protection
        is_critical = any(
            full_name.lower() == cr.lower() or repo.get("name", "").lower() == cr.lower()
            for cr in policy.critical_repos
        ) if policy.critical_repos else False
        approvals = 2 if is_critical else bp.required_approvals

        try:
            bpr = await github_admin.ensure_branch_protection(
                token,
                full_name,
                branch=default_branch,
                required_approvals=approvals,
                require_code_owner_reviews=bp.require_code_owner_reviews,
                dismiss_stale_reviews=bp.dismiss_stale_reviews,
                require_status_checks=bp.require_status_checks,
                block_force_pushes=bp.block_force_pushes,
                restrict_push_teams=bp.restrict_push_teams,
            )
            bpr["critical"] = is_critical
            bpr["approvals_required"] = approvals
            report.branch_protections.append(bpr)
        except Exception as exc:
            report.errors.append({
                "step": "branch_protection",
                "repo": full_name,
                "error": str(exc),
            })

        # 4. CODEOWNERS
        try:
            cor = await github_admin.ensure_codeowners(
                token, full_name, policy.codeowners_content, branch=default_branch,
            )
            report.codeowners.append(cor)
        except Exception as exc:
            report.errors.append({
                "step": "codeowners",
                "repo": full_name,
                "error": str(exc),
            })

        # 5. PR + Issue templates
        templates = [
            (".github/pull_request_template.md", policy.pr_template, "chore: add PR template"),
            (".github/ISSUE_TEMPLATE/bug_report.md", policy.bug_template, "chore: add bug report template"),
            (".github/ISSUE_TEMPLATE/feature_request.md", policy.feature_template, "chore: add feature request template"),
        ]
        for file_path, content, commit_msg in templates:
            try:
                tr = await github_admin.ensure_repo_file(
                    token, full_name, file_path, content, commit_msg, branch=default_branch,
                )
                report.templates.append(tr)
            except Exception as exc:
                report.errors.append({
                    "step": "template",
                    "repo": full_name,
                    "file": file_path,
                    "error": str(exc),
                })

    logger.info(
        "Governance applied: org=%s repos=%d teams=%d errors=%d",
        org, len(active_repos), len(policy.teams), len(report.errors),
    )
    return report
