from fastapi import APIRouter

from app.api.v1.endpoints import (
    admin,
    agents,
    api_keys,
    approvals,
    auth,
    automation,
    briefing,
    commands,
    contacts,
    control,
    dashboard_kpi,
    data_collection,
    departments,
    email,
    executions,
    export,
    finance,
    github,
    goals,
    governance,
    health,
    inbox,
    innovation,
    integrations,
    intelligence,
    layers,
    locations,
    media,
    memory,
    mfa,
    notes,
    notifications,
    observability,
    ops,
    ops_incident,
    orgs,
    performance,
    projects,
    search,
    slack_commands,
    social,
    tasks,
    users,
    webhooks,
)

api_router = APIRouter()

api_router.include_router(health.router)
api_router.include_router(admin.router)
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(approvals.router)
api_router.include_router(agents.router)
api_router.include_router(memory.router)
api_router.include_router(briefing.router)
api_router.include_router(email.router)
api_router.include_router(orgs.router)
api_router.include_router(commands.router)
api_router.include_router(tasks.router)
api_router.include_router(notes.router)
api_router.include_router(projects.router)
api_router.include_router(goals.router)
api_router.include_router(contacts.router)
api_router.include_router(control.router)
api_router.include_router(data_collection.router)
api_router.include_router(inbox.router)
api_router.include_router(intelligence.router)
api_router.include_router(executions.router)
api_router.include_router(integrations.router)
api_router.include_router(finance.router)
api_router.include_router(layers.router)
api_router.include_router(observability.router)
api_router.include_router(ops.router)
api_router.include_router(ops_incident.router)
api_router.include_router(export.router)
api_router.include_router(search.router)
api_router.include_router(github.router)
api_router.include_router(social.router)
api_router.include_router(notifications.router)
api_router.include_router(mfa.router)
api_router.include_router(webhooks.router)
api_router.include_router(api_keys.router)
api_router.include_router(dashboard_kpi.router)
api_router.include_router(automation.router)
api_router.include_router(slack_commands.router)
api_router.include_router(departments.router)
api_router.include_router(performance.router)
api_router.include_router(governance.router)
api_router.include_router(media.router)
api_router.include_router(locations.router)
api_router.include_router(innovation.router)
