from fastapi import APIRouter

from app.api.v1.endpoints import (
    activity_goals,
    activity_timeline,
    admin,
    admin_purge,
    agents,
    api_keys,
    approval_workflows,
    approvals,
    audit_trail,
    auth,
    automation,
    briefing,
    bulk,
    bulk_action_logs,
    call_logs,
    campaigns,
    coaching,
    commands,
    commissions,
    competitors,
    contact_lifecycle,
    contact_merge_logs,
    contact_relationships,
    contact_score_history,
    contact_segments,
    contact_timeline_events,
    contacts,
    contracts,
    control,
    conversion_funnels,
    custom_fields,
    custom_reports,
    customer_health,
    dashboard_kpi,
    dashboard_widgets,
    data_collection,
    data_retention,
    deal_collaborators,
    deal_dependencies,
    deal_forecast,
    deal_requirements,
    deal_risks,
    deal_rotations,
    deal_splits,
    deal_velocity,
    deals,
    decision_cards,
    dedup_rules,
    departments,
    document_signing,
    document_templates,
    drip_analytics,
    drip_campaigns,
    duplicate_detection,
    email,
    email_analytics,
    email_sequences,
    email_suppressions,
    email_templates,
    email_warmup,
    empire_digital,
    enrichment_queue,
    executions,
    export,
    feature_requests,
    field_audit,
    finance,
    forecast_rollups,
    forecast_scenarios,
    forms,
    github,
    goal_cascades,
    goals,
    governance,
    health,
    import_export_presets,
    import_mappings,
    inbox,
    innovation,
    integrations,
    intelligence,
    internal_comments,
    knowledge_base,
    layers,
    lead_score_rules,
    leaderboard,
    leads,
    locations,
    media,
    meeting_notes,
    meetings,
    memory,
    mfa,
    notes,
    notification_rules,
    notifications,
    observability,
    onboarding,
    ops,
    ops_incident,
    orchestrator,
    orgs,
    outbound_webhooks,
    performance,
    personas,
    pipeline_snapshots,
    playbooks,
    product_bundles,
    products,
    projects,
    quote_approvals,
    quotes,
    rate_limit_configs,
    recurring_invoices,
    referrals,
    report_schedules,
    revenue_goals,
    revenue_recognition,
    role_dashboards,
    saved_filters,
    score_decay,
    scorecard,
    scoring_rules,
    search,
    share_packets,
    sla_policies,
    slack_commands,
    social,
    stage_gates,
    stripe_webhooks,
    subscriptions,
    surveys,
    tags,
    tasks,
    team_quotas,
    territories,
    territory_assignments,
    user_activity_heatmap,
    users,
    webhook_deliveries,
    webhook_events,
    webhook_retries,
    webhooks,
    win_loss,
    workflow_observability,
    workspace_permissions,
    workspaces,
)

api_router = APIRouter()

api_router.include_router(health.router)
api_router.include_router(admin.router)
api_router.include_router(admin_purge.router)
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(approvals.router)
api_router.include_router(agents.router)
api_router.include_router(memory.router)
api_router.include_router(briefing.router)
api_router.include_router(email.router)
api_router.include_router(empire_digital.router)
api_router.include_router(leads.router)
api_router.include_router(orgs.router)
api_router.include_router(commands.router)
api_router.include_router(tasks.router)
api_router.include_router(notes.router)
api_router.include_router(projects.router)
api_router.include_router(goals.router)
api_router.include_router(contacts.router)
api_router.include_router(control.router)
api_router.include_router(data_collection.router)
api_router.include_router(inbox.router)
api_router.include_router(intelligence.router)
api_router.include_router(executions.router)
api_router.include_router(integrations.router)
api_router.include_router(finance.router)
api_router.include_router(bulk.router)
api_router.include_router(layers.router)
api_router.include_router(observability.router)
api_router.include_router(ops.router)
api_router.include_router(ops_incident.router)
api_router.include_router(export.router)
api_router.include_router(search.router)
api_router.include_router(github.router)
api_router.include_router(social.router)
api_router.include_router(notifications.router)
api_router.include_router(mfa.router)
api_router.include_router(webhooks.router)
api_router.include_router(api_keys.router)
api_router.include_router(dashboard_kpi.router)
api_router.include_router(automation.router)
api_router.include_router(slack_commands.router)
api_router.include_router(departments.router)
api_router.include_router(performance.router)
api_router.include_router(personas.router)
api_router.include_router(coaching.router)
api_router.include_router(governance.router)
api_router.include_router(media.router)
api_router.include_router(locations.router)
api_router.include_router(innovation.router)
api_router.include_router(workspaces.router)
api_router.include_router(share_packets.router)
api_router.include_router(decision_cards.router)
api_router.include_router(orchestrator.router)
api_router.include_router(deal_forecast.router)
api_router.include_router(deal_requirements.router)
api_router.include_router(deals.router)
api_router.include_router(campaigns.router)
api_router.include_router(scoring_rules.router)
api_router.include_router(notification_rules.router)
api_router.include_router(report_schedules.router)
api_router.include_router(workspace_permissions.router)
api_router.include_router(activity_timeline.router)
api_router.include_router(custom_fields.router)
api_router.include_router(email_templates.router)
api_router.include_router(contact_segments.router)
api_router.include_router(outbound_webhooks.router)
api_router.include_router(workflow_observability.router)
api_router.include_router(stripe_webhooks.router)
api_router.include_router(sla_policies.router)
api_router.include_router(enrichment_queue.router)
api_router.include_router(approval_workflows.router)
api_router.include_router(tags.router)
api_router.include_router(import_export_presets.router)
api_router.include_router(internal_comments.router)
api_router.include_router(dashboard_widgets.router)
api_router.include_router(duplicate_detection.router)
api_router.include_router(recurring_invoices.router)
api_router.include_router(role_dashboards.router)
api_router.include_router(webhook_deliveries.router)
api_router.include_router(contact_lifecycle.router)
api_router.include_router(saved_filters.router)
api_router.include_router(bulk_action_logs.router)
api_router.include_router(data_retention.router)
api_router.include_router(score_decay.router)
api_router.include_router(scorecard.router)
api_router.include_router(deal_velocity.router)
api_router.include_router(team_quotas.router)
api_router.include_router(webhook_retries.router)
api_router.include_router(field_audit.router)
api_router.include_router(rate_limit_configs.router)
api_router.include_router(email_sequences.router)
api_router.include_router(deal_risks.router)
api_router.include_router(contact_relationships.router)
api_router.include_router(pipeline_snapshots.router)
api_router.include_router(user_activity_heatmap.router)
api_router.include_router(document_templates.router)
api_router.include_router(goal_cascades.router)
api_router.include_router(commissions.router)
api_router.include_router(contact_score_history.router)
api_router.include_router(deal_collaborators.router)
api_router.include_router(email_suppressions.router)
api_router.include_router(forms.router)
api_router.include_router(meeting_notes.router)
api_router.include_router(revenue_recognition.router)
api_router.include_router(products.router)
api_router.include_router(contracts.router)
api_router.include_router(competitors.router)
api_router.include_router(email_analytics.router)
api_router.include_router(territories.router)
api_router.include_router(referrals.router)
api_router.include_router(knowledge_base.router)
api_router.include_router(quotes.router)
api_router.include_router(surveys.router)
api_router.include_router(playbooks.router)
api_router.include_router(import_mappings.router)
api_router.include_router(deal_rotations.router)
api_router.include_router(webhook_events.router)
api_router.include_router(custom_reports.router)
api_router.include_router(subscriptions.router)
api_router.include_router(drip_campaigns.router)
api_router.include_router(lead_score_rules.router)
api_router.include_router(onboarding.router)
api_router.include_router(forecast_scenarios.router)
api_router.include_router(feature_requests.router)
api_router.include_router(audit_trail.router)
api_router.include_router(customer_health.router)
api_router.include_router(meetings.router)
api_router.include_router(document_signing.router)
api_router.include_router(leaderboard.router)
api_router.include_router(dedup_rules.router)
api_router.include_router(stage_gates.router)
api_router.include_router(activity_goals.router)
api_router.include_router(call_logs.router)
api_router.include_router(drip_analytics.router)
api_router.include_router(deal_splits.router)
api_router.include_router(contact_merge_logs.router)
api_router.include_router(product_bundles.router)
api_router.include_router(forecast_rollups.router)
api_router.include_router(conversion_funnels.router)
api_router.include_router(revenue_goals.router)
api_router.include_router(deal_dependencies.router)
api_router.include_router(contact_timeline_events.router)
api_router.include_router(email_warmup.router)
api_router.include_router(territory_assignments.router)
api_router.include_router(quote_approvals.router)
api_router.include_router(win_loss.router)
